POST http://localhost:3333/subscribe-to-event
Content-Type: application/json

{
  "name": "John Doe",
  "email": "john.doe@example.com"
}

###
POST http://localhost:3333/subscribe-to-event
Content-Type: application/json

{
  "name": "John Doe 3",
  "email": "john.doe3@example.com",
  "referrerId": "2c716427-1c08-4b6d-bca4-3cbe3b51c670"
}

###
POST http://localhost:3333/subscribe-to-event
Content-Type: application/json

{
  "name": "John Doe 4",
  "email": "john.doe4@example.com",
  "referrerId": "34eea686-9300-449d-9581-b484402c3c5a"
}



####
GET http://localhost:3333/invites/2c716427-1c08-4b6d-bca4-3cbe3b51c670


### 
GET http://localhost:3333/subscribers/2c716427-1c08-4b6d-bca4-3cbe3b51c670/ranking/clicks


####
GET http://localhost:3333/subscribers/2c716427-1c08-4b6d-bca4-3cbe3b51c670/ranking/count


###
GET http://localhost:3333/subscribers/2c716427-1c08-4b6d-bca4-3cbe3b51c670/ranking/position


###
GET http://localhost:3333/ranking


###
POST http://localhost:3333/send-message
Content-Type: application/json

{
  "message": "How many subscribers do you have?"
}